#!/bin/bash

SCREEN_NAME=minecraft_server
SERVER_PATH=$(realpath $(dirname $0))


screen -dmS $SCREEN_NAME bash -c "$SERVER_PATH/.startonce"
echo "${SCREEN_NAME}" > $SERVER_PATH/.screen


echo "Server started. Execute 'console' for manage it."
echo ""

