#!/bin/bash

SCREEN_NAME=minecraft_server
SERVER_PATH=$(realpath $(dirname $0))


if ! [ -f "./enabled" ];
then
    echo "The server is disabled. Rename the 'disabled' file to 'enabled'."
    echo ""

else
    screen -dmS $SCREEN_NAME bash -c "$SERVER_PATH/.start"
    echo "${SCREEN_NAME}" > $SERVER_PATH/.screen
fi


echo "Server started. Execute 'console' for manage it."
echo ""

